# TODO: Migrate this to .mypy.toml
# https://github.com/python/mypy/issues/18617
[mypy]
enable_error_code =
  ignore-without-code,
  redundant-expr,
  truthy-bool
follow_untyped_imports = True
strict = False
warn_redundant_casts = True
warn_unreachable = True
warn_unused_configs = True
